name: Container images

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  container_image:
    name: Container images for brokers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCLOUD_SERVICEACCOUNT_KEY }}

      - name: Docker metadata for memory-broker
        id: memory-broker
        uses: docker/metadata-action@v4
        with:
          images: gcr.io/triggermesh/memory-broker
          tags: |
            type=semver,pattern={{raw}}
            latest

      - name: Build and push memory-broker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: cmd/memory-broker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.memory-broker.outputs.tags }}
          labels: ${{ steps.memory-broker.outputs.labels }}

      - name: Docker metadata for redis-broker
        id: redis-broker
        uses: docker/metadata-action@v4
        with:
          images: gcr.io/triggermesh/redis-broker
          tags: |
            type=semver,pattern={{raw}}
            latest

      - name: Build and push redis-broker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: cmd/redis-broker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.redis-broker.outputs.tags }}
          labels: ${{ steps.redis-broker.outputs.labels }}
