name: E2e tests

on:
  workflow_run:
    workflows: [Container images]
    types:
    - completed

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis/redis-stack-server:latest
        ports:
        - 6379:6379
        env:
          REDIS_ARGS: "--appendonly yes"

        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - name: Go caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ github.job }}-${{ runner.os }}-go-

    - name: Launch e2e tests
      run: go test --count 1 -v ./test/e2e/... -tags e2e
