name: E2e tests

on:
  workflow_run:
    workflows: ["Container images"]
    types:
      - completed

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis/redis-stack-server:latest
        ports:
        - 6379:6379
        env:
          REDIS_ARGS: "--appendonly yes"

        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis-broker:
        image: gcr.io/triggermesh/redis-broker:${{ github.sha }}
        ports:
        - 8080:8080
        env:
          CONFIG_PATH: "/etc/triggermesh/broker.conf"
          REDIS_ADDRESS: 0.0.0.0:6379
        volumes:
        - "${GITHUB_WORKSPACE}/config/broker.conf:/etc/triggermesh/broker.conf"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - name: Copy initial broker config
      run: |
        bash "${GITHUB_WORKSPACE}/tests/e2e/apply-config.sh"

    - name: Start broker from code
      run: |
        sleep 5;
        go run ./cmd/redis-broker start \
          --redis.address "localhost:${{ job.services.redis.ports[6379] }}" \
          --config-path "${GITHUB_WORKSPACE}/.local/config.yaml"
